# Spam Email Classifier
In this notebook, we will evaluate different ML models for email classification

## 1: Imports and Load Data

In [20]:
import warnings 
warnings.simplefilter('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
df = pd.read_csv("data.csv")

In [22]:
df.head()

   label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

## 2: Data Preprocessing

In [23]:
df.shape

(83448, 2)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 83448 entries, 0 to 83447
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   83448 non-null  int64
 1   text    83448 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.3 MB

In [25]:
df.isnull().sum()

label    0
text     0
dtype: int64

In [26]:
X = df['text']
Y = df['label']

In [27]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=3)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

# makes 10000 features at max 
# ignores words appearing in more than 80 percent doc
# ignore words appearing in just 1 doc
# Ignore english stock words like the, is, and

tf = TfidfVectorizer(max_features=10000, max_df=0.8, min_df = 1, stop_words='english', lowercase = True)

X_train_features = tf.fit_transform(X_train)
X_test_features  = tf.transform(X_test)

## 3: Model Training

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [31]:
# Logistic Regression

lr = LogisticRegression()
lr.fit(X_train_features, Y_train)
lr_train = lr.predict(X_train_features)
lr_test = lr.predict(X_test_features)

# Decision Trees 

dtrees = DecisionTreeClassifier()
dtrees.fit(X_train_features, Y_train)
dt_train = dtrees.predict(X_train_features)
dt_test = dtrees.predict(X_test_features)

# K Nearest Neighbors

knn = KNeighborsClassifier()
knn.fit(X_train_features, Y_train)
knn_train = knn.predict(X_train_features)
knn_test = knn.predict(X_test_features)

# Random Forest

rf = RandomForestClassifier()
rf.fit(X_train_features, Y_train)
rf_train = rf.predict(X_train_features)
rf_test = rf.predict(X_test_features)

## 4: Evaluation

In [33]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [34]:
# Logistic Regression

lr_train_acc = accuracy_score(Y_train, lr_train)
lr_test_acc  = accuracy_score(Y_test, lr_test)
lr_precision = precision_score(Y_test, lr_test)
lr_recall    = recall_score(Y_test, lr_test)
lr_f1        = f1_score(Y_test, lr_test)

# Decision Trees

dt_train_acc = accuracy_score(Y_train, dt_train)
dt_test_acc  = accuracy_score(Y_test, dt_test)
dt_precision = precision_score(Y_test, dt_test)
dt_recall    = recall_score(Y_test, dt_test)
dt_f1        = f1_score(Y_test, dt_test)

# K Nearest Neighbors

knn_train_acc = accuracy_score(Y_train, knn_train)
knn_test_acc = accuracy_score(Y_test, knn_test)
knn_precision = precision_score(Y_test, knn_test)
knn_recall = recall_score(Y_test, knn_test)
knn_f1 = f1_score(Y_test, knn_test)

# Random Forest 

rf_train_acc = accuracy_score(Y_train, rf_train)
rf_test_acc = accuracy_score(Y_test, rf_test)
rf_precision = precision_score(Y_test, rf_test)
rf_recall = recall_score(Y_test, rf_test)
rf_f1 = f1_score(Y_test, rf_test)

In [36]:
evaluation = pd.DataFrame({
  "Model": ["Logistic Regression", "Decision Tree", "KNN", "Random Forest"],
  "Train Accuracy": [lr_train_acc, dt_train_acc, knn_train_acc, rf_train_acc],
  "Test Accuracy": [lr_test_acc, dt_test_acc, knn_test_acc, rf_test_acc],
  "Precision": [lr_precision, dt_precision, knn_precision, rf_precision],
  "Recall": [lr_recall, dt_recall, knn_recall, rf_recall],
  "F1 Score": [lr_f1, dt_f1, knn_f1, rf_f1]
})

evaluation

,Model,Train Accuracy,Test Accuracy,Precision,Recall,F1 Score
0,Logistic Regression,0.988541,0.984661,0.979953,0.991277,0.985582
1,Decision Tree,0.999626,0.964170,0.966021,0.966240,0.966130
2,KNN,0.875550,0.842660,0.772332,0.996148,0.870077
3,Random Forest,0.999611,0.984721,0.983966,0.987198,0.985579

Conclusion: Logistic Regression seems to be performing the best as it has good scores across the board. I will be using it for deployment.

## 5: Deployment

In [37]:
import pickle

my_object = {
    "vectorizer": tf,
    "model": lr
}
with open('my_file.pkl', 'wb') as file:
    pickle.dump(my_object, file)